version: '3.4'

services:
  dockerllm:
    container_name: ai_engine
    image: docker-llm
    build:
      context: ./services/ai_engine
      dockerfile: Dockerfile
    # TODO - Change to ENV variables
    volumes:
      - /Users/bharatsesham/Documents/speech_data:/data/speech_data
    ports:
      - 5001:5001
      - 5002:5002
    env_file:
      - ./.env

  superset:
    build:
      context: ./services/superset
      dockerfile: dockerfile.superset
    container_name: superset
    volumes:
      - ./services/superset/superset_config.py:/app/superset/superset_config.py
      - ./services/superset/superset-init.sh:/app/superset-init.sh
      - ./services/superset/metadata:/home/superset
    command: [ "/app/superset-init.sh" ]
    ports:
      - "8088:8088"
    env_file:
      - ./.env
    depends_on:
      # TODO: Change DB to postgres for scalability
      # - postgres
      - redis
    platform: linux/x86_64

  # TODO: Check for cache working process
  redis:
    image: redis:5.0.5-alpine
    container_name: redis

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot-challenges:/etc/letsencrypt
      - certbot-challenges:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dockerllm
      - superset

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-challenges:/var/www/certbot
      - certbot-challenges:/etc/letsencrypt
      - ./infrastructure/certbot/init-certbot.sh:/init-certbot.sh
      # TODO - Made it a service -> seperate docker and renewal logic. Check if ngnix update when creds are renewd. Intial Cred logic is to 
    entrypoint: "/bin/sh -c '/init-certbot.sh'"
    depends_on:
      - nginx
    environment:
      - CERTBOT_EMAIL=bharat.sesham11@gmail.com
      - CERTBOT_DOMAIN1=api.bharatsesham.com
      - CERTBOT_DOMAIN2=superset.bharatsesham.com

volumes:
  certbot-challenges:
    # TODO: Make a custom network for all the services

