apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infrastructure/k8s-manifests/ai_engine/ai-engine-deployment.yaml
  - infrastructure/k8s-manifests/ai_engine/ai-engine-service.yaml
  - infrastructure/k8s-manifests/ai_engine/ai-engine-claim0-persistentvolumeclaim.yaml
  # - superset/superset-deployment.yaml
  # - superset/superset-service.yaml
  # - superset/superset-pvcs/superset-claim0-persistentvolumeclaim.yaml
  # - superset/superset-pvcs/superset-claim1-persistentvolumeclaim.yaml
  # - superset/superset-pvcs/superset-claim2-persistentvolumeclaim.yaml
  # - redis/redis-deployment.yaml
  # - nginx/nginx-deployment.yaml
  # - nginx/nginx-service.yaml
  # - nginx/nginx-claim0-persistentvolumeclaim.yaml
  # - certbot/certbot-deployment.yaml
  # - certbot/pvcs/certbot-challenges-persistentvolumeclaim.yaml
  # - certbot/pvcs/certbot-claim2-persistentvolumeclaim.yaml
  - infrastructure/k8s-manifests/configmaps/env-configmap.yaml
  - infrastructure/k8s-manifests/secrets/env-secrets.yaml
  - infrastructure/k8s-manifests/kubernetes-dashboard/dashboard-adminuser.yaml

