apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: certbot
  name: certbot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: certbot
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/obsidian-default: "true"
        io.kompose.service: certbot
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - /init-certbot.sh
          env:
            - name: CERTBOT_DOMAIN1
              value: api.bharatsesham.com
            - name: CERTBOT_DOMAIN2
              value: superset.bharatsesham.com
            - name: CERTBOT_EMAIL
              value: bharat.sesham11@gmail.com
          image: certbot/certbot
          name: certbot
          volumeMounts:
            - mountPath: /var/www/certbot
              name: certbot-challenges
            - mountPath: /etc/letsencrypt
              name: certbot-challenges
            - mountPath: /init-certbot.sh
              name: certbot-claim2
      restartPolicy: Always
      volumes:
        - name: certbot-challenges
          persistentVolumeClaim:
            claimName: certbot-challenges
        - name: certbot-challenges
          persistentVolumeClaim:
            claimName: certbot-challenges
        - name: certbot-claim2
          persistentVolumeClaim:
            claimName: certbot-claim2
