apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: ai-engine
  name: ai-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: ai-engine
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/obsidian-default: "true"
        io.kompose.service: ai-engine
    spec:
      containers:
        - env:
            - name: ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: ADMIN_EMAIL
                  name: env
            - name: ADMIN_FIRSTNAME
              valueFrom:
                configMapKeyRef:
                  key: ADMIN_FIRSTNAME
                  name: env
            - name: ADMIN_LASTNAME
              valueFrom:
                configMapKeyRef:
                  key: ADMIN_LASTNAME
                  name: env
            - name: ADMIN_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: ADMIN_USERNAME
                  name: env
            - name: AUDIO_ROOT
              valueFrom:
                configMapKeyRef:
                  key: AUDIO_ROOT
                  name: env
            - name: DEV_PORT
              valueFrom:
                configMapKeyRef:
                  key: DEV_PORT
                  name: env
            - name: DEV_URL
              valueFrom:
                configMapKeyRef:
                  key: DEV_URL
                  name: env
            - name: HOSTED_IP
              valueFrom:
                configMapKeyRef:
                  key: HOSTED_IP
                  name: env
            - name: NGROK_AUTH_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: NGROK_AUTH_TOKEN
                  name: env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: PROD_PORT
              valueFrom:
                configMapKeyRef:
                  key: PROD_PORT
                  name: env
            - name: PROD_URL
              valueFrom:
                configMapKeyRef:
                  key: PROD_URL
                  name: env
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: env
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  key: REGION
                  name: env
            - name: SPEECH_SAVE_LOCATION
              valueFrom:
                configMapKeyRef:
                  key: SPEECH_SAVE_LOCATION
                  name: env
            - name: SQLALCHEMY_DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  key: SQLALCHEMY_DATABASE_URI
                  name: env
            - name: SUPERSET_CONFIG_PATH
              valueFrom:
                configMapKeyRef:
                  key: SUPERSET_CONFIG_PATH
                  name: env
            - name: SUPERSET_HOME
              valueFrom:
                configMapKeyRef:
                  key: SUPERSET_HOME
                  name: env
            - name: relative_audio_path
              valueFrom:
                configMapKeyRef:
                  key: relative_audio_path
                  name: env
            - name: NGROK_AUTH_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: NGROK_AUTH_TOKEN
                  optional: true 
            - name: SUPERSET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SUPERSET_SECRET_KEY
                  name: env-secrets
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: OPENAI_API_KEY
                  name: env-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-secrets
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: ACCESS_KEY
                  name: env-secrets
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: env-secrets
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: ADMIN_PASSWORD
                  name: env-secrets
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY
                  name: env-secrets
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_KEY
                  name: env-secrets
          name: ai-engine
          image: bharatsesham/ai_engine:v1.0
          ports:
            - containerPort: 5001
              hostPort: 5001
              protocol: TCP
            - containerPort: 5002
              hostPort: 5002
              protocol: TCP
          volumeMounts:
            - mountPath: /data/speech_data
              name: ai-engine-claim0
      restartPolicy: Always
      volumes:
        - name: ai-engine-claim0
          persistentVolumeClaim:
            claimName: ai-engine-claim0
