apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: ai-engine
  name: ai-engine
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
    - name: "5002"
      port: 5002
      targetPort: 5002
  selector:
    io.kompose.service: ai-engine
