AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ShippingAddressTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ShippingAddress
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: region
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: RegionIndex
          KeySchema:
            - AttributeName: region
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

