FROM apache/superset

USER root
# Install additional Python packages
RUN pip install pydynamodb 
RUN pip install python-dotenv

# Install Ngrok
RUN apt-get update && apt-get install -y unzip && \
    curl -Lo ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip && \
    unzip ngrok.zip && \
    rm ngrok.zip
