apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: certbot-challenges
  name: certbot-challenges
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
